create schema kch_lookup authorization dba
create memory table kch_lookup.context(id integer primary key,context varchar(50) not null,defaultvalue varchar(100),lastupdatedby varchar(50),lastupdatedtime timestamp)
create memory table kch_lookup.lookup(id integer primary key,contextid integer not null,key varchar(50) not null,value varchar(100),startdate date not null,enddate date,lastupdatedby varchar(50),lastupdatedtime timestamp)
insert into kch_lookup.context (id, context, defaultvalue) values (1, 'context1', 'default for context 1')
insert into kch_lookup.context (id, context, defaultvalue) values (2, 'context2', 'default for context 2')
insert into kch_lookup.context (id, context, defaultvalue) values (3, 'context3', 'default for context 3')
insert into kch_lookup.context (id, context, defaultvalue) values (4, 'context4', 'default for context 4')
insert into kch_lookup.context (id, context, defaultvalue) values (5, 'context5', 'default for context 5')
insert into kch_lookup.lookup (id, contextid, key, value, startdate) values (1, 1, 'key1', 'value1', current_date)
insert into kch_lookup.lookup (id, contextid, key, value, startdate) values (2, 1, 'key2', 'value2', current_date)
insert into kch_lookup.lookup (id, contextid, key, value, startdate) values (3, 1, 'key3', 'value3', current_date)
insert into kch_lookup.lookup (id, contextid, key, value, startdate) values (4, 1, 'key4', 'value4', current_date)
insert into kch_lookup.lookup (id, contextid, key, value, startdate) values (5, 2, 'key5', 'value5', current_date)
insert into kch_lookup.lookup (id, contextid, key, value, startdate) values (6, 2, 'key6', 'value6', current_date)
